#!/usr/bin/env python3
"""
Generate C/C++ register-parameter probe functions and a manifest for objdump checking.
"""

from __future__ import annotations

import json
import os
import textwrap

ROOT = os.path.dirname(os.path.abspath(__file__))
GEN = os.path.join(ROOT, "generated")

DATA_REGS = [f"d{i}" for i in range(8)]
ADDR_REGS = [f"a{i}" for i in range(7)]  # a0..a6

DATA_TYPES = [
    ("ulong", "ULONG", "return v;"),
    ("long", "LONG", "return (ULONG)v;"),
    ("uword", "UWORD", "return (ULONG)v;"),
    ("word", "WORD", "return (ULONG)v;"),
    ("ubyte", "UBYTE", "return (ULONG)v;"),
    ("byte", "BYTE", "return (ULONG)v;"),
    ("enum", "RP_RGBFTYPE", "return (ULONG)v;"),
]

DATA_TYPES_CXX_EXTRA = [
    ("enum_class", "RP_PixelFormat", "return (ULONG)v;"),
]

ADDR_TYPES = [
    ("aptr", "APTR", "return (ULONG)p;"),
    ("void_ptr", "void *", "return (ULONG)p;"),
    ("ubyte_ptr", "UBYTE *", "return (ULONG)p;"),
]

PATTERNS = {
    # Matches boardinfo.h CalculateBytesPerRow / ResolvePixelClock / SetPanning order.
    "calc_bpr": {
        "params": [
            ("a0", "APTR", "bi"),
            ("d0", "ULONG", "width"),
            ("d1", "ULONG", "height"),
            ("a1", "APTR", "mi"),
            ("d7", "FMT", "format"),
        ],
        "return_expr": "return (ULONG)format;",
        "check_reg": "d7",
    },
    "resolve_pixclk": {
        "params": [
            ("a0", "APTR", "bi"),
            ("a1", "struct ModeInfoStub *", "mi"),
            ("d0", "ULONG", "clockIdx"),
            ("d7", "FMT", "format"),
        ],
        "return_expr": "return (ULONG)format;",
        "check_reg": "d7",
    },
    "set_panning": {
        "params": [
            ("a0", "APTR", "bi"),
            ("a1", "APTR", "mem"),
            ("d0", "UWORD", "width"),
            ("d1", "WORD", "x"),
            ("d2", "WORD", "y"),
            ("d7", "FMT", "format"),
        ],
        "return_expr": "return (ULONG)format;",
        "check_reg": "d7",
    },
    "set_panning_d1": {
        "params": [
            ("a0", "APTR", "bi"),
            ("a1", "APTR", "mem"),
            ("d0", "UWORD", "width"),
            ("d1", "WORD", "x"),
            ("d2", "WORD", "y"),
            ("d7", "ULONG", "format"),
        ],
        "return_expr": "return (ULONG)(UWORD)x;",
        "check_reg": "d1",
    },
}

FMT_TYPES = [
    ("ulong", "ULONG"),
    ("enum", "RP_RGBFTYPE"),
]

FMT_TYPES_CXX = FMT_TYPES + [("enum_class", "RP_PixelFormat")]


def reg_macro(reg: str, name: str, typ: str) -> str:
    kind = "A" if reg.startswith("a") else "D"
    num = reg[1:]
    return f"__REG{kind}{num}({typ} {name})"


def sym(lang: str, reg: str, typ: str, variant: str) -> str:
    return f"rp_{lang}_{reg}_{typ}_{variant}"


def header(lang: str) -> str:
    lines = [
        "/* Auto-generated by gen_probes.py — do not edit. */",
        '#include "regparm_macros.h"',
        '#include "regparm_types.h"',
        "",
    ]
    if lang == "cxx":
        lines += ['extern "C" {', ""]
    return "\n".join(lines)


def footer(lang: str) -> str:
    if lang == "cxx":
        return "\n} /* extern \"C\" */\n"
    return "\n"


def emit_single_probes(lang: str) -> tuple[list[str], list[dict]]:
    body: list[str] = []
    manifest: list[dict] = []

    for reg in DATA_REGS:
        types = list(DATA_TYPES)
        if lang == "cxx":
            types += DATA_TYPES_CXX_EXTRA
        for tname, ctype, ret in types:
            s = sym(lang, reg, tname, "single")
            body.append(
                f"ULONG ASM {s}({reg_macro(reg, 'v', ctype)}) {{ {ret} }}"
            )
            manifest.append(
                {
                    "symbol": s,
                    "lang": lang,
                    "reg": reg,
                    "type": tname,
                    "variant": "single",
                    "expect_reg": reg,
                }
            )

    for reg in ADDR_REGS:
        for tname, ctype, ret in ADDR_TYPES:
            s = sym(lang, reg, tname, "single")
            body.append(
                f"ULONG ASM {s}({reg_macro(reg, 'p', ctype)}) {{ {ret} }}"
            )
            manifest.append(
                {
                    "symbol": s,
                    "lang": lang,
                    "reg": reg,
                    "type": tname,
                    "variant": "single",
                    "expect_reg": reg,
                }
            )

    return body, manifest


def emit_pattern_probes(lang: str) -> tuple[list[str], list[dict]]:
    body: list[str] = []
    manifest: list[dict] = []

    fmt_types = FMT_TYPES_CXX if lang == "cxx" else FMT_TYPES

    for pname, pspec in PATTERNS.items():
        if pname == "set_panning_d1":
            params = []
            for reg, typ, name in pspec["params"]:
                params.append(reg_macro(reg, name, typ))
            s = sym(lang, pspec["check_reg"], "word", pname)
            sig = ", ".join(params)
            body.append(f"ULONG ASM {s}({sig}) {{ {pspec['return_expr']} }}")
            manifest.append(
                {
                    "symbol": s,
                    "lang": lang,
                    "reg": pspec["check_reg"],
                    "type": "word",
                    "variant": pname,
                    "expect_reg": pspec["check_reg"],
                }
            )
            continue

        for tname, fmt_type in fmt_types:
            params = []
            for reg, typ, name in pspec["params"]:
                t = fmt_type if typ == "FMT" else typ
                params.append(reg_macro(reg, name, t))
            s = sym(lang, pspec["check_reg"], tname, pname)
            sig = ", ".join(params)
            body.append(f"ULONG ASM {s}({sig}) {{ {pspec['return_expr']} }}")
            manifest.append(
                {
                    "symbol": s,
                    "lang": lang,
                    "reg": pspec["check_reg"],
                    "type": tname,
                    "variant": pname,
                    "expect_reg": pspec["check_reg"],
                }
            )

    return body, manifest


def write_lang(lang: str) -> list[dict]:
    ext = "c" if lang == "c" else "cpp"
    parts = [header(lang)]
    manifest: list[dict] = []

    single, m1 = emit_single_probes(lang)
    pattern, m2 = emit_pattern_probes(lang)
    manifest.extend(m1)
    manifest.extend(m2)

    parts.append("\n".join(single))
    parts.append("\n/* --- P96-shaped multi-arg patterns --- */\n")
    parts.append("\n".join(pattern))
    parts.append(footer(lang))

    out = os.path.join(GEN, f"probes_{lang}.{ext}")
    with open(out, "w", encoding="utf-8") as f:
        f.write("\n".join(parts))
    return manifest


def main() -> None:
    os.makedirs(GEN, exist_ok=True)
    manifest = write_lang("c") + write_lang("cxx")
    manifest_path = os.path.join(GEN, "manifest.json")
    with open(manifest_path, "w", encoding="utf-8") as f:
        json.dump(manifest, f, indent=2)
        f.write("\n")
    print(f"Generated {len(manifest)} probes -> {GEN}/")


if __name__ == "__main__":
    main()
